# -*- coding: utf-8 -*-
Description={"monster.name.1": 'Dilloom',
"monster.desc.1": 'Dilloom curls up into a ball to defend themselves from predators. Their tail works as a root and is able to absorb water.',
"monster.name.2": 'Dynamouse',
"monster.desc.2": 'Dynamouse ignites its fuse when angry or to keep others warm. When the fuse burns up, they can breathe extremely hot fire. They can also scatter highly explosive powder from the inside of their body.',
"monster.name.3": 'Nageel',
"monster.desc.3": 'Nageel lives in large groups in burrows below the seafloor. They poke their heads out of from their burrows whenever something approaches, which makes groups of them look like a garden.',
"monster.name.4": 'Eekape',
"monster.desc.4": 'Eekape is the spirits of decapitated humans. They wander the earth looking for their family from the past life. They scare everyone away with their horrendous stench.',
"monster.name.5": 'Palytid',
"monster.desc.5": 'Palytid waddles around on the seafloor, its small green blots glowing in the dark. It converts the little light it gathers to energy to survive.',
"monster.name.6": 'Mianari',
"monster.desc.6": 'Mianari lives in desert areas and hides underground when predators are spotted. They absorb lightning with their tail during storms.',
"monster.name.7": 'Berrball',
"monster.desc.7": 'Berrball produces a large amount of silk, due to having an enormous appetite for berry plants. Once they grow enough silk, they stay inside it until they evolve.',
"monster.name.8": 'Cesstoid',
"monster.desc.8": 'Cesstoid spends most of the time gathering food. It grows very fast, as it is capable of consuming more than its body size every day.',
"monster.name.9": 'Mizumi',
"monster.desc.9": 'Mizumi is extremely docile Etheremon. They doze off in the morning but get increasingly active nearing night time.',
"monster.name.10": 'Chulember',
"monster.desc.10": 'Chulember spit flames whenever they feel threatened. They live at high altitudes, where they melt the ice to get to the vegetation beneath it.',
"monster.name.11": 'Geckno',
"monster.desc.11": 'Geckno makes nearby predators fall asleep using their telepath powers. Directly looking at one can cause lightheadedness, sometimes even resulting in loss of consciousness.',
"monster.name.12": 'Blockid',
"monster.desc.12": 'Blockid has large hands used to block attacks. They train together by basically high-fiving each other. In a group, the Blockid with the largest hands is the leader.',
"monster.name.13": 'Thermolophus',
"monster.desc.13": 'Thermolophus devour various types of minerals and rocks. The heat inside their stomach melts them down to their basic components.',
"monster.name.14": 'Keradon',
"monster.desc.14": 'Keradon soar for great distances after jumping from cliffs. Their impressive stature is easily noticed along the horizon. Keradon is often trained for traveling purposes.',
"monster.name.15": 'Vermillios',
"monster.desc.15": 'Vermillios reflects sunlight to create beautiful illusions. These illusions lure and blind prey, making it fairly easy for them to obtain food. No big predators dare come close to Vermillios.',
"monster.name.16": 'Vivorin',
"monster.desc.16": "In its Wrath Form, Vivorin's arms grow into wings, capable of summoning strong whirlwinds. Its cry becomes deafening as it approaches.",
"monster.name.17": 'Windora',
"monster.desc.17": "Windora's beauty is unrivaled in the Etheremon world. It is said that its wind will calm the most troubled hearts.",
"monster.name.18": "Geenee",
"monster.desc.18": "Geenee is very common. Their claws are too small to be used properly, so it mostly attacks with its head when angry. Their fur grows a lot during the winter.",
"monster.name.19": "Quillster",
"monster.desc.19": "Quillster is capable of launching sharp quills form a long distance with high precision. Their launched quills will grow back within a day. When these quills have time to grow, they can reach a length of a meter.",
"monster.name.20": "Baulder",
"monster.desc.20": "Baulder carry around a rock given to them soon after birth by its parents. They gnaws on this rock every chance they get, as it seems to sharpen their teeth.",
"monster.name.22": "Vibe",
"monster.desc.22": "It is said that Vibe comes from another dimension. It is weak but possesses the ability to see through a short future. In the combat, Vibe becomes a great supporter as it can see the next moves of the opponents.",
"monster.name.23": "Swifty",
"monster.desc.23": "Not much is known about Swifty. This mysterious creature hides in the shadows. It uses wisps from its bright, misty red collar to trick lost travelers to go deeper into the woods.",
"monster.name.24": "Pangrass",
"monster.desc.24": "Pangrass eats so many leaves that it turns green. It usually spends the whole day eating and the next day to digest the food. When getting mad, Pangrass uses its huge body to block the opponent.",
"monster.name.25": "Mintol",
"monster.desc.25": "Mintol can be found in the northern regions of Etheremon World in great numbers. They breath out cold air, keeping the temperature around them below zero. Mintol leaves are often used in tea and different types of candy.",
"monster.name.26": "Omnom",
"monster.desc.26": "Omnom are found in rustling grass patches, making them easy to find. Their licks can heal wounded Etheremon. Omnom are shaped like Rare Candies.",
"monster.name.27": "Kyari",
"monster.desc.27": "Any group of Kyari are engulfed in an aroma similar to one specific type of scented candle. Kyari are easily domesticated, mostly for their aromatic attributes.",
"monster.name.28": "Lectrobe",
"monster.desc.28": "Lectrobe use their electrical charge to form an arm with slightly physical properties. Their punches feel like high-voltage shocks, and blow back opponents easily. Lectrobe are presumably a product of human experiments.",
"monster.name.29": "Mirrie",
"monster.desc.29": "Mirrie are said to be the ghosts of vain people. They can't be seen via mirrors. Mirrie often follow around people and Etheremons they find pretty.",
"monster.name.30": "Cobrus",
"monster.desc.30": "Cobrus are said to protect their trainer from harm. They are nowadays rarely found in the wild. Ancient drawings depicted Cobrus and its evolution as holy.",
"monster.name.31": "Lollipunch",
"monster.desc.31": "Lollipunch deliver fierce blows with their strong arm, while the other is normally used to feint attacks. It catches foes off guard by delivering a second blow swiftly after the first.",
"monster.name.32": "Odwig",
"monster.desc.32": "Odwig are born with a hard shell, that grows bigger over time, to fit its transformation, Occlusk. Odwig don't respond to most sounds, but notice the smallest objects that hit its shell.",
"monster.name.33": "Tygloo",
"monster.desc.33": "Tygloo wander frozen plains in search for food in groups, often lead by a Mechloo. Their helmet-like heads are very durable, and are their main form of defense.",
"monster.name.34": "Pudde",
"monster.desc.34": "Pudde are found in rivers and seas, coloured exactly like the water they live in. They keep the waters they live in clear and clean.",
"monster.name.35": "Mushmite",
"monster.desc.35": "Mushmite are both aloof and mysterious, and are often found clustered in groups muttering to themselves. They become easily annoyed by travelers who mistake them for a normal kind of mushroom.",
"monster.name.36": "Polynimo",
"monster.desc.36": "Polynimo is capable of creating a powerful and dangerous wind-vortex, with speeds up to 40-72 mph, even though you would not expect it from her tiny wings.",
"monster.name.37": "Fuirrel",
"monster.desc.37": "Fuirrel can sleep anywhere by wrapping themselves in their incredibly soft tail. Its tail grows bigger when it gets older, and will keep growing until it transforms.",
"monster.name.38": "Dillow",
"monster.desc.38": "Dillow release poisonous fumes when they feel threatened. They can curl up to roll at high speed. Their tail can absorb water to create a liquid used to poison enemies.",
"monster.name.39": "Pyrode",
"monster.desc.39": "Pyrode's rocket-like body enables them to reach high speeds. They can breathe flames and smoke to attack or escape. They're extremely agile and can fit practically anywhere.",
"monster.name.40": "Moranagi",
"monster.desc.40": "Moranagi lead smaller fish into their burrows, where they can easily be cornered and consequently devoured. They tend to hide among groups of Nageel to attack anything that dares to approach them.",
"monster.name.41": "Moldec",
"monster.desc.41": "Moldec have a slug-like body formed by moldy flesh, leaving behind a foul, slimy trail wherever they go. The only thing they want is to find the body they once possessed.",
"monster.name.42": "Oculid",
"monster.desc.42": "Oculid travel in herdes along the seafloor, their glowing blots lighting up the area wherever they go. Their poison can take down the largest of predators.",
"monster.name.43": "Surinari",
"monster.desc.43": "Surinari gain energy by absorbing lightning with their tail. They protect their young at all cost from predators. Surinari are very caring in general, but become alarmed easily.",
"monster.name.44": "Silvyx",
"monster.desc.44": "Silvyx have grown wings capable of small periods of flight. Their thick silk-like fur provides them with great defensive capabilities. Silvyx can propose a serious threat to berry farmers due to their insane appetite.",
"monster.name.45": "Coronoid",
"monster.desc.45": "Coronoid manipulate other Etheremon to gather food for them. They tend to get highly aggresive if their needs aren't fulfilled, which happens often, due to the insane amounts of food they eat.",
"monster.name.46": "Watadzumi",
"monster.desc.46": "Watadzumi presumably spread deathly disease a long time ago. At the time, the people gave blame to a sort of foul air, but a mixture of both seemed to be the case, as Watadzumi whip up a strong wind wherever they appear.",
"monster.name.47": "Fuenago",
"monster.desc.47": "Fuenago live at high altitudes, were they can survive low temperatures due to their fur coat. The flames on their body grow bigger when they feel threatened, to intimidate enemies.",
"monster.name.48": "Geckelic",
"monster.desc.48": "Geckelic are capable of putting their enemies to sleep, but can also cause insane hallucinations and headaches. Their eyes are 400 times as sensitive as the human eye and can see colours even at night. They appear to have existed since ancient times.",
"monster.name.49": "Blockall",
"monster.desc.49": "Blockall have giant hands that can easily take the greatest of hits. They are often used by trainers as a punching bag, to train themselves and their Blockall at the same time.",
"monster.name.50": "Geerex",
"monster.desc.50": "Geerex often fight each other in the wild, but can be tamed very easily. Their fur keeps them warm during winter. Geerex are mostly trained by younger seekers.",
"monster.name.51": "Dredrock",
"monster.desc.51": "Dredrock live deep inside caves. They find their way using soundwaves and vibrations through the ground. An appetite for certain red rocks seems to have changed their appearance over time.",
"monster.name.52": "Florost",
"monster.desc.52": "Florost keep their body insulated by growing leaves to stay cold. Florost are often the leader of a group of Mintol. Their leaves are used in tea and candy.",
"monster.name.53": "Yumee",
"monster.desc.53": "Yumee try to make friends everywhere and can heal others with their licks. They love to eat sweets and berries and grow hyperactive when eating to much.",
"monster.name.54": "Candeliria",
"monster.desc.54": "Candeliria spread an aroma capable of causing hallucinations, warping vision or inhibiting movement. These Etheremons can thus be dangerous when not trained properly.",
"monster.name.55": "Wrektric",
"monster.desc.55": "Wrektric evolved to become apolar, losing their magnetic properties, but gaining powerful electrical charge divided over two plasmatic arms. Wrektric dish out painful punches, followed by a thunderous sound.",
"monster.name.56": "Reflectre",
"monster.desc.56": "Reflectre are said to be the cause of vanity, as well as low self esteem. They cause visions warping the truth, making people and Etheremon believe lies. Reflectre can only be seen via mirrors.",
"monster.name.57": "Dracobra",
"monster.desc.57": "Dracobra are rare Etheremon, only seen deep inside ancient temples. Not much is know about them. They were regarded as holy by an ancient civilization.",
"monster.name.58": "Mawverize",
"monster.desc.58": "Its long arms allow it to hit foes trying to avoid close combat. Mawverize can open its left fist in order to grab and subsequently swing its opponent around.",
"monster.name.59": "Occlusk",
"monster.desc.59": "Occlusk hide in their extremely durable shell to protect itself from attackers. The power with which their shell closes can break bones. Occlusk can't hear anything when their shell is closed.",
"monster.name.60": "Mechloo",
"monster.desc.60": "Mechloo are often the leader of a group of Tygloo. Their ice-clad body protects them from most physical attacks. Some believe Mechloo are simply Tygloo in a mech.",
"monster.name.61": "Aquary",
"monster.desc.61": "Aquary can colour the water they live in to reflect their mood, ranging from a deep dark blue when they're sad to a bright pink when they're happy.",
"monster.name.62": "Squake",
"monster.desc.62": "Squake have extremely heavy tails, and use them to attack potential predators. They live on or under the ground, since their heavy tail disables them to climb trees.",
"monster.name.63": "Qairrel",
"monster.desc.63": "Qairrel have very light tails, and use them to attack swiftly and move gracefully. They live high up in trees, and can often be seen gliding between them.",
"monster.name.64": "Dillossus",
"monster.desc.64": "Dillossus can curl up into a ball to protect itself or to roll down hills at high speed. The poisonous fumes they excrete can be deadly depending on their mood. Dillossus are also known for providing shelter to smaller Etheremon.",
"monster.name.65": "Raxplode",
"monster.desc.65": "Raxplode can breath high temperature ashes to suffocate and blind enemies. They can run at insane speeds, leaving behind a flaming trail. These Etheremons have an advanced sense of smell and can detect anything through thick smoke, clouds of ash or in the dark.",
"monster.name.66": "Dehedra",
"monster.desc.66": "Dehedra are spirits in search of the deheaded body they possessed in a past life. They mostly eat rotting food, but they can't resist the taste of a moldy corpse. Dehedra litterally smell like death.",
"monster.name.67": "Aphroxid",
"monster.desc.67": "Aphroxid stay still and low among a herd of Palytid and Oculid. Once its prey approaches, it attacks with high speed, its four pale white jaws clamping the prey, releasing a strong, deathly toxin into the blood.",
"monster.name.68": "Tekagon",
"monster.desc.68": "Tekagon roam their territory in search of plants to eat. They are blind, but can feel vibrations through the ground from great distances. Tekagon recognize the vibrations their family gives off.",
"monster.name.69": "Aromerita",
"monster.desc.69": "Aromerita leave behind their aroma wherever they walk. This aroma is capable of healing wounds. Since Aromerita are barely found in the wild, their leaves are very valuable.",
"monster.name.70": "Liscious",
"monster.desc.70": "Liscious have extraordinary saliva, containing components with amazing healing properties. They are attracted to sweets, and can get very dangerous when they aren't fed any for a long time.",
"monster.name.71": "Resurvy",
"monster.desc.71": "Resurvy has grown sturdier and more solid than before. Its magical properties have grown in strength, and its bigger tail allows for swift movement underwater.",
"monster.name.72": "Morinori",
"monster.desc.72": "Morinori are most often kept as household Etheremon, providing company for those alone at home. In some cultures, they're believed to protect their home from evil spirits. Others are convinced Morinori bring luck to the people they live with.",
"monster.name.73": "Gremin",
"monster.desc.73": "Gremin spread around a type of fairy dust that induces a deep sleep. Parts of the desert inhabited by these Etheremon are rarely traveled... or, at least, not awake. Gremin are referred to as 'sandmen' in fairytales.",
"monster.name.74": "Spoxin",
"monster.desc.74": "Spoxin shrouds its enemies with its strong foul gas, making them nauseous or knocking them out. Spoxin are very friendly and try to make friends with other Etheremon, but their stench drives them away.",
"monster.name.75": "Intelix",
"monster.desc.75": "Legend has it that Intelix appears upon the birth of every being blessing it with talents and qualities, giving it its personality. And upon death it comes to guide the soul to the underworld, taking the gifts back in order to be reused in another soul's next life.",
"monster.name.76": "Lilspri",
"monster.desc.76": "According to folklore, Lilspri are lost souls of children found wandering through forests trying to find their way home. They have a strange behavior of crying in the same spot, which is thought to be where their human body have died before turning into a Lilspri.",
"monster.name.77": "Inkami",
"monster.desc.77": "An Inkami created an island north of the world with the help of two golems. As soon as the Inkami was done, it went into a deep slumber somewhere on the island.",
"monster.name.78": "Redhandit",
"monster.desc.78": "Redhandit are presumed to have been crooks in a previous life, due to their kleptomania being apparent immediately after hatching. Their eyes are located on their hands, while their face bears a fake pair.",
"monster.name.79": "Endorr",
"monster.desc.79": "Endorr live deep underground, where they produce their own nutrients by converting the minerals they feed on. Their appendages can grow in length to fit their use. Endorr grow to fill out their rocky exterior, and evolve when they outgrow it.",
"monster.name.80": "Sonectid",
"monster.desc.80": "Sonectid are the fastest swimming Etheremon, due to their extremely strong hind legs. Sonectid are very commonly used in Etheremon racing.",
"monster.name.81": "Cryptise",
"monster.desc.81": "Cryptise are supposedly burial urns possessed by the soul inside it. They float around at burial grounds, leaving a trail of ash behind them.",
"monster.name.82": "Tenteink",
"monster.desc.82": "In ancient folklore, an Inkami became Tenteink to defeat Osorochi, and banish it to a dark realm.",
"monster.name.83": "Criminiac",
"monster.desc.83": "Criminiac walk rather slowly, but their hands are deceptively quick. They seem to enjoy stealing expensive objects, due to which they are presumed to be the ghosts of kleptomaniacs.",
"monster.name.84": "Endrowth",
"monster.desc.84": "Endrowth grow their body outwards of their rocky exterior. They feed on minerals they find underground, glowing brightly upon consuming them.",
"monster.name.85": "Nuklectid",
"monster.desc.85": "Nuklectid grows hind legs that are even stronger than before, making it capable to reach insane speeds. Its exoskeleton grows tougher, and its segmented body allows it to turn around easier.",
"monster.name.86": "Cremortus",
"monster.desc.86": "Cremortus are dreaded Etheremon, rarely seen outside of burial sites or tombs. Cremortus feed on ashes and rocks, and occasionally, unknowing prey. They protect their tomb with their (second) life.",
"monster.name.87": "Monstratos",
"monster.desc.87": "Monstratos are entities consisting of multiple micro-organisms inhabiting a giant rock. Their various bodyparts are controlled from inside the rock. They devour chunks of metals and rocks to grow.",
"monster.name.88": "Duscre",
"monster.desc.88": "Duscre are only found deep inside tombs, where they seem to be the only one around. When Cremortus evolves into Duscre, the urn it leaves behind becomes a wild Cryptise.",
"monster.name.89": "Mapla",
"monster.desc.89": "The primary focus of these creatures is preservation of themselves and their off springs. They use their large bushy bodies to both camouflage and nest.",
"monster.name.90": "Barkindle",
"monster.desc.90": "Barkindle's body is very warm to hug. Kids, especially, and other Etheremon love to snuggle up to it. When angry, it will heat up and it's tail will be burning hot.",
"monster.name.91": "Wolflaze",
"monster.desc.91": "Their bodies are warm to touch, but when sick or angered, it may cause burns. In battle, it's wrists and tail flame up.",
"monster.name.92": "Wolverize",
"monster.desc.92": "The temperature of a Wolverize's flame can reach up to 1000 degree Celsius. They are known for their remarkable displays of fire.",
"monster.name.93": "Ruffski",
"monster.desc.93": "Because they are only found in northern areas, they like to play and run around all day to keep their body heat at a suitable temperature. They love to chase down Clastroid.",
"monster.name.94": "Arblizen",
"monster.desc.94": "The leader of a pack is determined by strength and the size of their ice collar. At times there are arguments and the competitor will often join a new pack.",
"monster.name.95": "Siberizen",
"monster.desc.95": "Known as the judge of the north, Siberizen is a powerful yet wise Etheremon. It chooses the fate of those found within its territory by its underlings.",
"monster.name.96": "Tundrill",
"monster.desc.96": "A major hazard for roads and urban areas in general. Twisting its body in a drilling motion, it can submerge into the ground in mere seconds.",
"monster.name.97": "Matara",
"monster.desc.97": "Matara live in shallow water, due to their inability to swim. Their body is covered in rusted iron barbs, so any damage it afflicts will result in an infected wound. Matara are normally very docile creatures though.",
"monster.name.98": "Matarama",
"monster.desc.98": "Matarama grows stronger legs to stand up straight, and bigger arms to increase its offensive capabilities. Defensively, its rusted metal shield changes into strong steel armour. It also opens its eyes, so it can see for a change.",
"monster.name.99": "Malakel’e",
"monster.desc.99": "Malakel'e gather under the moonlight to practice their chanting. It is said their chants can cause headaches, nausea, and give bad dreams to those who hear it.",
"monster.name.100": "Kahukel’e",
"monster.desc.100": "Kahukel'e acts as the chief of their group. There are usually up to three chief Kahukel'e per marching group. Kahukel'e are skilled fighters. They are able to detach their arms and use them as a weapon.",
"monster.name.101": "Tobeno",
"monster.desc.101": "Tobeno are protected by a sturdy shell, and can withstand strong attacks as a result. Tobeno are surprisingly speedy",
"monster.name.102": "Purem",
"monster.desc.102": "Puremu have grown out of their protective shell, but have replaced it with a thick layer of shock absorbing plumage. Puremu race each other for amusement.",
"monster.name.103": "Flaraton",
"monster.desc.103": "Flaraton generates intense heat inside its body when running at high speeds. It then has to release this heat by breathing fire. ",
"monster.name.104": "Inferacoon",
"monster.desc.104": "Inferacoon has better control of heat than its younger self, being able to release heat at will. It can store as much as one billion Joules of heat.",
"monster.name.105": "Scubella",
"monster.desc.105": "Scubella lift from the ocean surface and let the winds take them wherever it blows. They are also known to fall in the hands of strangers they are attracted to unexpectedly on their journeys.",
"monster.name.106": "Ekopi",
"monster.desc.106": "It lives in open eucalypt woodlands. Ekopi love to climb up the trees and eat the leaves that make up most of its diet. They like to craft various objects and weapons with leaves and twigs.",
"monster.name.107": "Ekoraft",
"monster.desc.107": "It uses tree branches as weapons, landing multiple blows on the enemy. Ekoraft are very protective and will protect its home with its life.",
"monster.name.108": "Expertri",
"monster.desc.108": "Expertri have mastered every form of tool making. It is said that a single Expertri is responsible for the protection of a whole forest.",
"monster.name.109": "Purgast",
"monster.desc.109": "Purgast is said to create a second life for everyone, based on their actions in life. Purgast enjoys its destiny to the fullest. When happy enough, Purgast is said to transform, to end life for good.",
"monster.name.110": "Smeltal",
"monster.desc.110": "Smeltal can shoot fire from the tips of its fingers. It consumes flammable materials, such as wood, to keep its flame lit. If Smeltal's inner flame was to go out it would become like that of a statue until its flame was lit again.",
"monster.name.111": "Vorvosip",
"monster.desc.111": "Vorvosip locates its prey by using its heat-sensing proboscis. Once it locates its prey, it will swoop down towards it in high speeds and paralyze it with a numbing fluid before feeding. Females are more aggressive than males.",
"monster.name.112": "Devostoric",
"monster.desc.112": "In the waters of Prehistoric Orohn, Devostoric was an apex predator. Due to its heavy plating, the Devostoric was a slow but powerful swimmer and relied heavily on its strong beaked mouth to capture food. The great force of their jaw is capable of damaging the hardest of metals.",
"monster.name.113": "Sauntler",
"monster.desc.113": "Sauntler are known to wander around cemeteries. It is said to visit each grave and have a connection with lost spirits.",
"monster.name.114": "Zapillar",
"monster.desc.114": "In groups, Zapillar are cared for by a single Zaptenna that tend to them by sharing energy with them through the transferring touch of antennae.",
"monster.name.115": "Infiluv",
"monster.desc.115": "Infiluv is said to be born from the strong love and bond of two magical lovers centuries ago. According to legend, it used all its power to bring love and peace to end the war between the four Elemental Beasts. Infiluv can mend broken hearts.",
"monster.name.116": "Krubble",
"monster.desc.116": "Krubble communicate with each other by blowing bubbles from their pincers. They make amusing bubble shows on seashores when reunited.",
"monster.name.117": "Krabboul",
"monster.desc.117": "Its shell has strengthened upon evolution. Coral starts growing from its body helping it to blend into its habitat.",
"monster.name.118": "Capareef",
"monster.desc.118": "It protects the coral reef where it  inhabits with devotion to keep it unharmed. Its shell becomes harder as it gets older.",
"monster.name.119": "Tipsillar",
"monster.desc.119": "Tipsillar live in big groups where they make elaborated movements to hypnotize their possible predators. Their 'dancing' combined with their vibrant colours look surrealistic from the distance.",
"monster.name.120": "Mesmerhys",
"monster.desc.120": "Its spikes are its best defense against possible predators. It lives in colonies near the sea shores forming enormous barriers and reefs.",
"monster.name.121": "Chromothic",
"monster.desc.121": "They live in underground tunnels where their electric energy is the only source of light. The flashing of their noses vary depending of what they try to communicate.",
"monster.name.122": "Grubgas",
"monster.desc.122": "When Grubgas feels threatened it shoots a dense curtain of a dense foul smell to escape. Its gas toxicity depends of their diet.",
"monster.name.123": "Polupa",
"monster.desc.123": "They are always in a defensive posture waiting for evolution, anything considered a threat will be blown away with an explosion of toxic gas.",
"monster.name.124": "Noxibeet",
"monster.desc.124": "Their hard shell and poisonous artillery makes Noxibeet almost like a war machine. Their biology inspired the design of war arsenals.",
"monster.name.125": "Kelpony",
"monster.desc.125": "Thought to be extinct, a large group was recently found in the Havai region. Kelpony can be found near lively reefs, feeding on algae and seaweed.",
"monster.name.126": "Chevalage",
"monster.desc.126": "Perfectly adapted to its habitat, this Etheremon has developed seaweed-like appendages to blend in with its surroundings. It acted as a ferry in the old times.",
"monster.name.127": "Reefallion",
"monster.desc.127": "Any coral reef that is inhabited by a Reefallion is said to be of pristine beauty. Its rock-like appendages become harder as it ages.",
"monster.name.128": "Lemeeni",
"monster.desc.128": "It swings from the branches of tall trees where it lives, It stares directly to stuff it likes.",
"monster.name.129": "Lemeeglar",
"monster.desc.129": "Lemeeglar believes that the leaves that grow on its tail have healing properties, It confuses enemies with erratic movements when battling.",
"monster.name.130": "Primasham",
"monster.desc.130": "Primasham believes that it can foresee events and put foes in a trance by just waving its tails. Ancient cultures worshiped Primasham because of its mysterious and amazing powers.",
"monster.name.131": "Iquander",
"monster.desc.131": "Iquander love catching sunlight to warm up their body and compete with each other for the best spot.",
"monster.name.132": "Iquanaze",
"monster.desc.132": "Iquanaze’s scale can reach a very high temperature, burning anything that touches. Its readiness to battle is as big as its ego.",
"monster.name.133": "Wrecktile",
"monster.desc.133": "Its pride and combat abilities are well known by Etheremon seekers. Wrecktile slams and throws away foes with great technique and fiery attacks showing its volatile energy.",
"monster.name.134": "Mindallion",
"monster.desc.134": "Ancient stories mention Mindallion forming part of  Gods and Godesses belongings. Its gem glows in presence of powerful beings.",
"monster.name.135": "Talisment",
"monster.desc.135": "These Etheremon have lived on earth since the beginning of cultures, They keep the secrets of every era they witnessed on their crystals.",
"monster.name.136": "Krakowee",
"monster.desc.136": "They live in ponds and lakes, where they float on the surface and barely walk on land. It camouflages with ease in the swamp environment.",
"monster.name.137": "Alligwamp",
"monster.desc.137": "They were often mistaken as swamp monsters in old times, Their coverage makes them difficult to see in the marshlands where they inhabit.",
"monster.name.138": "Felistar",
"monster.desc.138": "Its believed that they come from outer space, big groups of them are seen falling from the skies like shooting stars once a year.",
"monster.name.139": "Galaleo",
"monster.desc.139": "Myths say that they were once a part of the cosmos and ruled galaxies for centuries. They have a strong connection with the space and the stars.",
"monster.name.140": "Dusprite",
"monster.desc.140": "It travels through entire forests spreading spores that help plants grow. Its body also produces toxin that it uses as defense.",
"monster.name.141": "Spoxie",
"monster.desc.141": "Despite its cute appearance and kind behaviour, Spoxie produces extremely toxic spores in its body which it uses at a last resource to protect itself when needed.",
"monster.name.142": "Clothom",
"monster.desc.142": "It is believed that this Etheremon is made of spirits of tailors and seamstresses of antique times. They haunt houses and made them their place to live.",
"monster.name.143": "Blankos",
"monster.desc.143": "They haunt houses pretending to be normal pieces of cloth and scare those who enter, Their body structure is still a mystery.",
"monster.name.144": "Pistaccoul",
"monster.desc.144": "Its shell protects it from the harshness that it may encounter in the forest where it inhabits, due to its rareness not much is known about Pistaccouls.",
"monster.name.145": "Fantasnut",
"monster.desc.145": "Not much is known about this mysterious etheremon. There are stories that claim that Fantasnuts were responsible for missing explorers when they got deep in the woods.",
"monster.name.146": "Kikapole",
"monster.desc.146": "They are often seen fighting with other Kikapoles for mere fun, Their legs and tail are their best weapon.",
"monster.name.147": "Ribibrawl",
"monster.desc.147": "Its kicking abilities match up those of Blaziken's, Their fighting has a double purpose: to train and to have fun.",
"monster.name.148": "Vexigon",
"monster.desc.148": "Vexigon can be quite a handful for Trainers. They like causing ruckus and disobeying commands. These stubborn Etheremon can go hours or even days of causing trouble.",
"monster.name.149": "Noxareo",
"monster.desc.149": "Noxareo enjoy causing ruckus for their own amusement. These troublesome Etheremon are known for causing damage with their reckless behavior. ",
"monster.name.150": "Darcastro",
"monster.desc.150": "These Etheremon soar across the land, compelling local Etheremon to rampage around. Sightings of them are immediately followed with city-wide warnings. ",
"monster.name.151": "Greipawn",
"monster.desc.151": "Its purpose in life is to serve and be a loyal companion. It is able to fight tirelessly to protect any being that it considers its superior.",
"monster.name.152": "Vitisir",
"monster.desc.152": "They are prideful and picky as they are often seen commanding big troops of Greipawns to fulfil their desires.",
"monster.name.153": "Vernirox",
"monster.desc.153": "A beast of destruction known as a Divine Act of God who once wreaked havoc using its earth power. It was punished for its great damage.",
"monster.name.154": "Quadrossal",
"monster.desc.154": "A beast of destruction known as a Divine Act of God who once wreaked havoc using its glacial hydro power. It was punished for its great damage.",
"monster.name.155": "Zedakazm",
"monster.desc.155": "The Realm of Zedakazm is the abode of the dead in which this beast is known as Ruler of the Underworld. It is known to bring evil souls to this bottomless realm where they will be tormented for eternity. ",
"monster.name.156": "Armadigoal",
"monster.desc.156": "It likes to roll all day long. Though beware and stay out of its way cause when it does it’s on fire",
"monster.name.157": "Armordigoal",
"monster.desc.157": "Armordigoal throws fireballs. Not many could get close to it in combat as its steel shell is one very powerful weapon.",
"monster.name.158": "Pangrove",
"monster.desc.158": "The biggest Etheremon on record on land. They have become increasingly aggressive over their generations as poachers has taken advantage of their kind nature",
"monster.name.159": "Kyberra",
"monster.desc.159": "Kyberra loves exploring the galaxy in search of Kyber crystals, its favourite snack. Legend has it that Kyberra is one of the fastest monsters that ever existed, and if you spot it, good fortune will follow you wherever you go.",
"monster.name.160": "Kyberram",
"monster.desc.160": "Legend has it that Kyberram possesses mysterious power of Kyber crystals. It moves like a beam of light and leaves crystal dust behind.",
"monster.name.161": "Pigperus",
"monster.desc.161": "Born from fractures of the ground, Pigperus has a magic sense like a radar on the ground around him, thereby increasing the accuracy of his stroke even when something blocks his view.",
"monster.name.162": "Boarazer",
"monster.desc.162": "Despite its arrogant appearance, Boarazer is warm and gentle. He possesses the power to transmute any material he touches into another state, such as turning stone into ice.",
"monster.name.163": "Piggicius",
"monster.desc.163": "Younger twin sister of Pigperus. Rumor has it that she has an ability to read the future and opponent’s thoughts, so she is aware of any potential danger around her or a dangerous attack beforehand, but there are also some who think it is due to her miraculous luck.",
"monster.name.164": "Wartoink",
"monster.desc.164": "Watoink spends most of its time swimming and it is unclear whether it is because she needs to be close to water, or she wants to have a fit body. She is highly intelligent yet very sensitive so you need to be careful to tame her.",
"monster.name.165": "Kumabag",
"monster.desc.165": "A half mechanical half stuffed bear with a human-like consciousness.  He's eternally cheesed off due to being constantly used as a bag! Be careful, his ego is as dangerous as his claws! Grrrr!",
"monster.name.166": "Spoulder",
"monster.desc.166": "They dwell in caves waiting for distracted preys, The crystals on their bodies are poisonous to the touch.",
"monster.name.167": "Cavachnid",
"monster.desc.167": "They build complex nests and webs with sediments their bodies produce, even making new caves in the process. Their poison is extremely powerful melting even rocks in matter or seconds.",
"monster.name.168": "Foxeez",
"monster.desc.168": "Foxeez, The Frosty mon, with ability to snow cloak itself from it's prey, an awesome and keen predator.",
"monster.name.169": "Coyoteez",
"monster.desc.169": "Foxeez evolves into Coyoteez the Frosty Ethermon, fear by most small games in the northern wild winter.",
"monster.name.170": "Roichirp",
"monster.desc.170": "It displays its coloured crest in order to appear more important among other Roichirp. The bigger and brighter the crest is, the more respected the Roichirp is.",
"monster.name.171": "Hawkrey",
"monster.desc.171": "Its crest is a symbol of their dominance so it takes care of it with devotion, They are often the second in charge of the flock after Emperazor's.",
"monster.name.172": "Emperazor",
"monster.desc.172": "Its magnificence became a symbol of royalty and elegance all across Zenev. Their feathers were used in the making of crowns for kings and queens in older times.",
"monster.name.173": "Batflare",
"monster.desc.173": "Dex Entry Pending..",
"monster.name.174": "Inferbat",
"monster.desc.174": "Dex Entry Pending..",
"monster.name.175": "Zyracier",
"monster.desc.175": "Dex Entry Pending..",
"monster.name.176": "Watuber",
"monster.desc.176": "Watuber are very playful and often like to amuse themselves in pools and near shores. Because they're not very good swimmers, they often borrow tubes and floaters.",
"monster.name.177": "Floatuber",
"monster.desc.177": "Dex Entry Pending..",
"monster.name.178": "Chambrawl",
"monster.desc.178": "Chambrawl do intense training for hours and hours a day. Their fists are powerful enough to break through boulders and bend steel.",
"monster.name.179": "Vaudequin",
"monster.desc.179": "It is said it haunts an abandoned Zenev Theater, Its aura brings joy and humour wherever it goes. Along with Capraclyst they make art.",
"monster.name.180": 'Muucopter',
"monster.desc.180": 'Flying santry of the Ethermon World, origins unknown, where do they come from?',
"monster.name.181": 'Boomergon',
"monster.desc.181": 'Interceptor vanguard, protector of the Ethermon World, perpetually scouting for something..',
"monster.name.182": 'Flairon',
"monster.desc.182": 'Bowing only to the Legendary Ethermons, Flarions powers are not be reckoned with, its judgements are considered absolute.',
"monster.name.183": 'Onchor',
"monster.desc.183": 'Onchoor are found in shallow water seashores as if remains of wrecked ships that have been sweeped across the timeless ocean, but alive they are of mystic power from the sea.',
"monster.name.184": 'Opmarine',
"monster.desc.184": 'Opmarine are ancient artifacts that have gain a consciousness, disguised as sharks they roam the open seas.',
"monster.name.185": 'Opsidien',
"monster.desc.185": 'Powerful ancient artifacts that have a mysterious link to all things living and dead, rumors has it that it carries the wealthiest of all treasures aboard.',
"monster.name.186": 'Sully',
"monster.desc.186": 'Sully roams the Ethermon freely, one of the most frequently found Ethermon other then Kyrai, Omnom, and Mintol.  It often stumble into adventure portals and turning up somewhere unexpected.',
"monster.name.187": 'Silica',
"monster.desc.187": 'Silica are found in Ethermon world, but a very rare to find ethermon, as most of them have lost them selves stumbled into some where else, the rest .. are still here roaming free.',
"monster.name.188": 'Sinexus',
"monster.desc.188": 'One of the most beautfiul creature in the Ethermon wolrd, with knowledge from vasts universe aboard, rumor has it that Sinexus have garnished the ability to travel between worlds though dimensional and unkown powers.',
"monster.name.189": 'Cannubis',
"monster.desc.189": 'Cannubis is known as the Phantom Leaf, this perennial pup travelled from the distant lands of Flowerpatch, where he served as a vigilant protector from pests.  This perennial pup can be fetched from the ether at the high time of the year.',
"monster.name.190": 'Keefo',
"monster.desc.190": 'Through accolades of victory and rigorous grinding, Keefo emerges as a stealthy shadow boxer with a fire in its eye.  Keefos mysterious aura have powerful effects such as keeping annoying pests and critters miles away.',
"monster.name.191": 'Duwat',
"monster.desc.191": 'The Warrior Shaman Ethermon, Duwat uses its otherworldly knowledge and prowess to traverse the battlefield.  Duwat are said to escort the souls of lost Mon through the Ether.',
"monster.name.192": 'Finray',
"monster.desc.192": 'Finray swims against strong currents by skillfully using its tail as a rudder. Its acute hearing allows it to evade any danger.',
"monster.name.193": 'Ogoprowl',
"monster.desc.193": 'Ogoprowl are known to dwell deep in underwater caves. Their glowing red eyes can pierce through the darkest areas.',
"monster.name.195": 'Sephysar',
"monster.desc.195": 'Sephysar are known to inhabit the mysterious Lake Altus. There goes a saying that whoever dares cross its territory will face great danger. It is able to harness the power of storms.',
"monster.name.196": 'Dorent',
"monster.desc.196": 'They live in pairs or in large groups. During summer they gather food and store it in the trunks of trees, preparing for the scarcity of winter.',
"monster.name.197": 'Grandorent',
"monster.desc.197": 'They spend most of their time up in trees where they build their homes. They enjoy just sitting atop trees and enjoying the view.',
"monster.name.198": 'Pricktile',
"monster.desc.198": 'They enjoy receiving sunlight anytime they can. It experiments a harsh fear when it is not stepping on land.',
"monster.name.199": 'Cactodon',
"monster.desc.199": 'They become stronger when the sun is shining bright. Their bodies are adapted to live with little water.',
"monster.name.200": 'Yarmeow',
"monster.desc.200": 'Yarmeow are very friendly and playful.  They unroll their tails and play with them when bored. Sometime when playing with other Yarmeow, their tails may get tangled with each other. ',
"monster.name.201": 'Tressemiao',
"monster.desc.201": 'It is very playful with it’s three soft-furred tails, weaving it in all kinds of wave. Baby Yarmeow like to play with their tails and snuggle under it for warmth.',
"monster.name.202": 'Naviumi',
"monster.desc.202": 'The tip of its tail is always pointing to the magnetic north of the globe, Naviumis memorize with precise accuracy any place they have been on or seen; migrating and storing food is an easy task for them.'}
